
name: Test (do not use this)

on: 
  workflow_dispatch:
    inputs:
      mhm:
        description: 'do not use this'
        required: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Updating APT
      run: sudo apt-get update
    - name: Installing some things
      run: apt list -a runc
